# Generated by Django 3.1.4 on 2020-12-13 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201213_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(default=11111111, max_length=8, validators=[django.core.validators.RegexValidator(message='Length has to be 8', regex='^.{8}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
