# Generated by Django 3.1.4 on 2020-12-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201213_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Book_model',
        ),
    ]
