# Generated by Django 3.1.4 on 2020-12-13 13:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201213_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_model',
            name='code',
        ),
        migrations.AlterField(
            model_name='book_model',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Length has to be 4', regex='^.{4}$')])),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='backend.book_model')),
            ],
        ),
    ]
