# Generated by Django 3.1.4 on 2020-12-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201214_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_model',
            name='quantity',
        ),
    ]
