# Generated by Django 3.1.4 on 2020-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_book_model_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
