# Generated by Django 3.1.4 on 2020-12-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201217_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='backend.user'),
        ),
    ]
